[main]
address = "31 Maltings Place, London, SW62BU"
search_radius_meters = 3000
max_flights = 20
max_elapsed_time = 1800
display_hold_time = 30

[logging]
max_activities = 500
categories = ["SYSTEM", "RADAR", "FLIGHT", "CONFIG", "ERROR", "INFO"]
